version: '3.5'

services:
  wordpress:
    image: wordpress
    restart: unless-stopped
    depends_on:
      - db
    env_file:
     - .env
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      LETSENCRYPT_HOST: ${DOMAINS}
      VIRTUAL_HOST: ${DOMAINS}
      VIRTUAL_NETWORK: ${NETWORK}
    volumes:
      - wordpress:/var/www/html

  db:
    image: mysql:9.4
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_RANDOM_ROOT_PASSWORD='1'
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
    driver: local
  db:
    driver: local
networks:
  default:
    external:
      name: ${NETWORK}
